//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCH.UnitTests.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCH.UnitTests.Resources.Files", typeof(Files).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;id&quot;: &quot;C0EC2J5T9&quot;,
        ///        &quot;name&quot;: &quot;evens-yndlingskanal&quot;,
        ///        &quot;created&quot;: &quot;1447318101&quot;,
        ///        &quot;creator&quot;: &quot;U0EBWMGG4&quot;,
        ///        &quot;is_archived&quot;: false,
        ///        &quot;is_general&quot;: false,
        ///        &quot;members&quot;: [
        ///            &quot;U0EBWMGG4&quot;,
        ///            &quot;U0F1RB87L&quot;,
        ///            &quot;U0F377V3J&quot;,
        ///            &quot;U0F3P72QM&quot;,
        ///            &quot;U0F6BAQ20&quot;,
        ///            &quot;U0F6BGXMJ&quot;,
        ///            &quot;U0F6DHYCV&quot;,
        ///            &quot;U0F6E9S1Z&quot;,
        ///            &quot;U0F6HD6AD&quot;,
        ///            &quot;U0F9B18HW&quot;,
        ///            &quot;U0LQB2KKL&quot;
        ///        ],
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string channels {
            get {
                return ResourceManager.GetString("channels", resourceCulture);
            }
        }
    }
}
